services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ProductsDB;User=sa;Password=My@Pasword1234;TrustServerCertificate=True;MultipleActiveResultSets=true
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "My@Pasword1234"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: